# Generated by Django 5.2.13 on 2026-05-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='description_short',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
